### ISSUE TITLE
Error After Enabling Themes

### ISSUE THREAD

**Issue by ukenmaulana** [scrisoft/crm#1]
Hi there, i've uploaded a theme named crm.zip
But suddenly when it enable, appear error like this.
![error themes](https://github.com/scrisoft/crm/assets/53071924/324b8788-2113-450e-90b6-f6e25d969d3f)

How to fix this ?

And could you tell me. The step from first to last if i need to instal wordpress pro.
I need multiple wordpress posting.
But i really confused with the step that i need to instal any component.
Please tell me the step.

**Comment by scrisoft** [comment]
Hi, you have installed a wrong theme in the user section. You have installed the theme for frontend area in the User's area.

Remove it

Please, just follow my videos. Don't guess how the things should be done. Same for plugin. Just look in the videos where I'm uploading the things.
